### ISSUE TITLE
Remote deck not working

### ISSUE THREAD

**Issue by bsappea** [AnKing-Memberships/anki-remote-decks#9]
#### Problem description

*Please describe the issue concisely in here. In case of an error: Walk us through the steps you took to get there. What happened? What did you expect to happen?*
When syncing remote decks this pop-up occurs: 

"Hey there! It seems an error has occurred while using the Remote Decks add-on.
The error was:
"'style'\nThe following deck failed to sync: Untitled document""
The add on worked for me for about a day and then started giving me issues while trying to sync. It suddenly stopped allowing me to add cards. As I add cards to the google doc in the appropriate format then sync remote decks each card added has a pop-up stating it can't be added. please help 

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [ x] I've restarted Anki to see if it helps
 - [ x] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [ x] I've tried to disable other add-ons to see if there are any interactions present
 - [ ] My issue disappears when I hold shift while starting Anki.
 - [ x] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### What Anki version are you using?

*Please open Anki, go to Help → About (windows) or Anki → About Anki (mac) to find the version. Edit the value between the backticks below

```
Version ⁨24.04.1 (ccd9ca1a)⁩
Python 3.9.18 Qt 6.6.2 PyQt 6.6.1
```

#### Error message (if any)

*If you've received an error message, please copy and paste it between the backticks below:*

```
Anki 24.04.1 (ccd9ca1a)  (ao)
Python 3.9.18 Qt 6.6.2 PyQt 6.6.1
Platform: macOS-11.7.9-x86_64-i386-64bit

Traceback (most recent call last):
  File "/Users/apple/Library/Application Support/Anki2/addons21/924929499/main.py", line 33, in sync_decks
    remote_deck = getRemoteDeck(current_remote_info["url"])
  File "/Users/apple/Library/Application Support/Anki2/addons21/924929499/parse_remote_deck.py", line 22, in getRemoteDeck
    deck = _parseHtmlPageToAnkiDeck(data)
  File "/Users/apple/Library/Application Support/Anki2/addons21/924929499/parse_remote_deck.py", line 47, in _parseHtmlPageToAnkiDeck
    orgData = _generateOrgListFromHtmlPage(data)
  File "/Users/apple/Library/Application Support/Anki2/addons21/924929499/parse_remote_deck.py", line 166, in _generateOrgListFromHtmlPage
    styles = img["style"]
  File "bs4.element", line 1573, in __getitem__
KeyError: 'style'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/apple/Library/Application Support/Anki2/addons21/924929499/__init__.py", line 53, in syncDecks
    raise e
  File "/Users/apple/Library/Application Support/Anki2/addons21/924929499/__init__.py", line 48, in syncDecks
    sync_decks()
  File "/Users/apple/Library/Application Support/Anki2/addons21/924929499/main.py", line 57, in sync_decks
    raise type(e)(str(e) + deckMessage).with_traceback(sys.exc_info()[2])
  File "/Users/apple/Library/Application Support/Anki2/addons21/924929499/main.py", line 33, in sync_decks
    remote_deck = getRemoteDeck(current_remote_info["url"])
  File "/Users/apple/Library/Application Support/Anki2/addons21/924929499/parse_remote_deck.py", line 22, in getRemoteDeck
    deck = _parseHtmlPageToAnkiDeck(data)
  File "/Users/apple/Library/Application Support/Anki2/addons21/924929499/parse_remote_deck.py", line 47, in _parseHtmlPageToAnkiDeck
    orgData = _generateOrgListFromHtmlPage(data)
  File "/Users/apple/Library/Application Support/Anki2/addons21/924929499/parse_remote_deck.py", line 166, in _generateOrgListFromHtmlPage
    styles = img["style"]
  File "bs4.element", line 1573, in __getitem__
KeyError: "'style'\nThe following deck failed to sync: Untitled document"

===Add-ons (active)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
AMBOSS add-on ['0amboss_addon', 2023-11-13T11:01, 'None', mod]
Additional Card Fields Fork for 21 ['744725736', 2022-10-23T05:10, 'None', mod]
Advanced Browser ['874215009', 2023-10-21T09:34, 'None', mod]
AnKing Note Types Easy Customization ['952691989', 2024-05-20T17:42, 'None', mod]
Anki Remote - Customize ['693153301', 2023-08-25T23:55, 'None', mod]
Anki Simulator ['817108664', 2023-11-06T11:26, 'None', '']
Anki Zoom ['538879081', 2020-04-03T19:20, 'v1.1.3', '']
AnkiHub ['1322529746', 2024-05-21T13:33, 'None', '']
Batch Editing ['291119185', 2023-10-25T19:38, 'None', '']
Clickable Tags v20 ['1739176371', 2022-01-30T16:58, 'None', '']
Convert Subdecks to Tag Hierarchy ['1172858842', 2023-02-07T12:15, 'None', '']
Countdown To Events and Exams ['1143540799', 2022-06-27T06:50, 'None', '']
Create Filtered Deck from the Browser ['861263371', 2019-03-01T21:14, 'None', '']
Custom Background Image and Gear Icon ['1210908941', 2023-04-18T20:19, 'None', mod]
Customize Keyboard Shortcuts ['24411424', 2023-11-01T04:17, 'None', mod]
Edit Field During Review Cloze ['385888438', 2024-01-03T01:19, '6.18', mod]
Extended Tag AddEdit Dialog ['1135507717', 2023-11-11T10:58, 'None', mod]
Fastbar- with nightmode support ['46611790', 2023-06-27T06:47, 'None', '']
Free Weekend - or Any Other Day ['742185195', 2022-05-18T19:53, 'None', mod]
Google Doc Decks Remote Decks ['924929499', 2024-05-04T20:58, 'None', mod]
High Yield Tags ['1918380616', 2023-01-10T13:14, 'None', mod]
Hint Hotkeys ['1844908621', 2023-04-14T09:13, 'None', '']
Image Editor ['307397307', 2022-09-07T23:09, 'None', mod]
Image Occlusion Enhanced ['1374772155', 2022-04-09T02:15, 'None', '']
Image Style Editor ['1593969147', 2021-12-17T01:01, 'None', mod]
ImageResizer ['1214357311', 2023-12-02T19:58, 'None', '']
Learning Step and Review Interval Retention ['1949865265', 2024-01-06T11:48, 'None', '']
Mini Format Pack ['295889520', 2023-11-02T13:00, 'None', '']
More Decks Stats and Time Left ['1556734708', 2024-04-11T05:35, 'None', mod]
More Overview Stats 21 ['738807903', 2021-07-30T14:13, 'None', mod]
Postpone cards review ['1152543397', 2023-04-14T21:29, 'None', '']
Puppy Reinforcement ['1722658993', 2023-11-16T06:59, 'None', '']
Quick Colour Changing ['2491935955', 2023-10-18T22:15, 'None', mod]
Refocus Card when Reviewing 21 ['1642550423', 2019-03-04T12:20, 'None', '']
Remote Decks Anki collaboration using Google Docs ['911568091', 2021-09-09T12:45, 'None', '']
Reset Ease ['947935257', 2023-11-11T19:22, 'None', '']
Special Fields ['1102281552', 2024-03-19T18:34, 'None', mod]
Speed Focus Mode auto-alert auto-reveal auto-answer ['1046608507', 2022-12-16T05:24, 'None', mod]
Symbols As You Type ['2040501954', 2024-01-19T23:42, 'None', '']
Symbols ['1461102936', 2024-02-10T10:53, 'None', mod]
The KING of Button Add-ons ['374005964', 2024-01-27T04:19, 'None', '']
The KING of Study Timers ['907028815', 2022-03-04T16:38, 'None', mod]
UpToDate Addon ['utd_anki_addon', 2023-05-08T10:16, 'None', '']
Web Browser - Search terms Import texts and images automatically ['864545277', 2023-11-17T13:28, 'None', mod]
Wrapper meta-addon ['396502676', 2023-07-22T07:05, 'None', mod]
when is next learning card due today due ['563204849', 2021-12-06T09:06, 'None', mod]

===IDs of active AnkiWeb add-ons===
1046608507 1102281552 1135507717 1143540799 1152543397 1172858842 1210908941 1214357311 1322529746 1374772155 1461102936 1556734708 1593969147 1642550423 1722658993 1739176371 1844908621 1918380616 1949865265 2040501954 24411424 2491935955 291119185 295889520 307397307 374005964 385888438 396502676 46611790 538879081 563204849 693153301 738807903 742185195 744725736 817108664 861263371 864545277 874215009 907028815 911568091 924929499 947935257 952691989

===Add-ons (inactive)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
Review Heatmap ['review_heatmap', 2020-04-30T08:23, 'None', '']
Simple Timer and Stopwatch for Anki 21 ['1423272642', 2018-01-24T17:03, 'None', '']
put ALL due learning cards first modified v2 support ['1807121582', 2019-11-24T13:20, 'None', '']



```

**Comment by AnKingMed** [comment]
I apologize for no response here. Were you able to get this working?
